{"uuid": "1c654194-2283-4ea4-950b-9cac467bd67d", "children": ["9fa66477-fd8b-46ec-a396-5ac959282934", "d3c3ec31-385c-40c7-9669-8ffdeafa1203"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service resources/geckodriver.exe unexpectedly exited. Status code was: 64\n\n", "trace": "  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\rubyk\\avactisProject\\testCases\\conftest.py\", line 12, in init_driver\n    value = webdriver.Firefox(executable_path=\"resources/geckodriver.exe\")\n  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 174, in __init__\n    self.service.start()\n  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 98, in start\n    self.assert_process_still_running()\n  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 110, in assert_process_still_running\n    raise WebDriverException(\n"}, "start": 1641812789203, "stop": 1641812791720}], "start": 1641812789203, "stop": 1641812791782}