{"uuid": "3ac744e7-2621-4067-be09-995f73777afd", "children": ["0decd0a0-f36d-425e-b645-05c675ac0cbd", "6fa9346e-d530-4778-9960-29dc92ed715d", "17424702-b28f-4d0d-85e8-588545fd7944"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"c:\\users\\rubyk\\virtual environmemts\\pycharmprojects\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\rubyk\\virtual environmemts\\pycharmprojects\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\rubyk\\virtual environmemts\\pycharmprojects\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\rubyk\\avactisProject\\testCases\\conftest.py\", line 14, in init_driver\n    value = webdriver.Chrome(executable_path=\"resources/chromedriver.exe\")\n  File \"c:\\users\\rubyk\\virtual environmemts\\pycharmprojects\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"c:\\users\\rubyk\\virtual environmemts\\pycharmprojects\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1618070106066, "stop": 1618070106082}], "start": 1618070106066, "stop": 1618070106551}