{"uuid": "8f335361-522a-43eb-8287-a8272b9f94a0", "children": ["c7d3fab5-fb86-4714-99db-bd68a80846ec", "6791ee15-0900-411c-8fca-0b4e387ac122"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service resources/geckodriver.exe unexpectedly exited. Status code was: 64\n\n", "trace": "  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\rubyk\\avactisProject\\testCases\\conftest.py\", line 12, in init_driver\n    value = webdriver.Firefox(executable_path=\"resources/geckodriver.exe\")\n  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 174, in __init__\n    self.service.start()\n  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 98, in start\n    self.assert_process_still_running()\n  File \"C:\\Users\\rubyk\\Virtual Environmemts\\New Venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 110, in assert_process_still_running\n    raise WebDriverException(\n"}, "start": 1641812783842, "stop": 1641812786359}], "start": 1641812783842, "stop": 1641812786640}